# To test meteoclimatic update:
#    python ../wfrender.py -f meteoclimatic.yaml -s ../../wfcommon/config/settings.yaml

init:
    storage: !service
        name: storage
        instance: !include
            path: ../../wfcommon/config/storage.yaml

renderer: !http
    root: !meteoclimatic
        id: YOUR_STATION_ID
        storage: !service
            name: storage

logging:
    level: info    
    handlers:
        default:
            level: debug
            handler: !include 
                path: ../../wfcommon/config/loghandler.yaml
                variables:
                    process: wfrender



