context:
    database: { url: 'localhost:/var/lib/firebird/2.0/data/wfrog.db' }
renderer: !http    
    root: !include
        path: default/24hours.yaml
    renderers:
        30days: !include
            path: default/30days.yaml
        365days: !include
            path: default/365days.yaml
    
