renderer: !http    
    root: !template
        path: templates/current-stats.html
        mime: text/html
        renderer: !multi
            renderers:
                days: !data
                    source: !simulator {} 
                    renderer: !multi
                        renderers:
                            temp_chart: !chart                            
                                series: 
                                    temp.max:
                                        color: peachpuff
                                        area: { to: temp.min }
                                        max: { color: darkred, text: darkred, thickness: 0.5 }
                                    temp.avg:                                 
                                        last: { thickness: 5, style: 'o' }
                                        order: 1                                        
                                    temp.min:
                                        color: None
                                        min: { color: blue, text: blue, thickness: 0.5 }
                                    dew.avg:
                                        color: darkcyan
                                        dash: 5                                        
                                labels: temp.lbl
                                zero: { color: gray, thickness: 0.5 }
                            temp_current: !value
                                key: temp
                                serie: avg
                                select: last
                hours: !data
                    source: !simulator {}
                    renderer: !multi
                        renderers:
                            wind_chart: !chart                                
                                series:
                                    wind.avg:                                        
                                        marks: {serie: wind.dir, color: gray, size: 12 }       
                                    wind.max:
                                        order: -1
                                        color: EEAAAA
                                        area: { color: peachpuff, to: wind.speed }                                    
                                        max: { color: darkred, text: darkred, thickness: 0.5 }
                                labels: wind.lbl
                                y_margin: [ 0, 1 ]
                            wind_now: !windradar
                                width: 125
                                height: 125
                                arrow: { show: yes }   
                                max: { color: EEAAAA, thickness: 4 }                             
                                trace: { color: lightgray, size: 10, ratio: 3, length: 3 }
                                beaufort: { color: lightgray, intensity: 0.3 }
                            wind_stat: !windradar
                                width: 200
                                height: 200
                                sectors: { color: lightgray }
                                lines: { gust: EEAAAA, thickness: 1 }
                                areas: {  gust: peachpuff }                              
