context:
    database: { url: 'file://database.db' }
    chart:
        bgcolor: 70BDF5
        color: indigo               
        text: indigo
        
renderer: !http    
    root: !template
        path: templates/current-stats.html
        mime: text/html
        renderer: !multi
            renderers:
                days: !data
                    #source: !daily { period: 30 }
                    source: !simulator {} 
                    renderer: !multi
                        renderers:
                            temp_chart: !chart                            
                                series: 
                                    temp.max:
                                        color: '9BCDF1'
                                        fill: { to: temp.min }
                                        max: { color: darkred, text: darkred, thickness: 0.5 }
                                    temp.avg:                                 
                                        last: { thickness: 5, style: 'o' }
                                        order: 1
                                    temp.min:
                                        color: '9BCDF1'
                                        min: { color: blue, text: blue, thickness: 0.5 }
                                    dew.avg:
                                        color: darkcyan
                                        thickness: 1
                                        dash: 5
                                        
                                labels: temp.lbl
                                zero: { color: gray, thickness: 0.5 }

                            temp_current: !value
                                key: temp
                                serie: avg
                                select: last
                hours: !data
                    #source: !hourly {period: 168}
                    source: !simulator {}
                    renderer: !multi
                        renderers:
                            wind_chart: !chart                                
                                series:
                                    wind.speed:                                        
                                        marks: {serie: wind.dir, size: 10 }       
                                    wind.gust:
                                        order: -1
                                        color: '9BCDF1'
                                        fill: { to: wind.speed }                                    
                                        max: { color: darkred, text: darkred, thickness: 0.5 }
                                labels: wind.lbl
                                y_margin: [ 0, 1 ]
                            wind_radar: !windradar
                                width: 300
                                height: 300
                                arrow: { color: black, thickness: 5 }   
                                max: { color: darkred, thickness: 8 }                             
                                tail: { color: grey }
                                trace: { color: green, size: 15, ratio: 3, length: 3 }
                                sectors: { color: darkcyan }
                                #bars: { color: blue, gust: red, thickness: 1 }
                                lines: { color: None, gust: red, thickness: 1 }
                                areas: { color: indigo, gust: FF222266 }
                                beaufort: { color: black, intensity: 0.15 }
                                
                                
                                
