context:
    database: { url: 'file://database.db' }
    chart_defaults:
        width: 200
        height: 125
        bgcolor: 70BDF5
        color: 1e2e6c
        
renderer: !http    
    root: !template
        path: templates/current-stats.html
        mime: text/html
        renderer: !multi
            renderers:
                days: !data
                    #source: !daily { period: 30 }
                    source: !simulator {} 
                    renderer: !multi
                        renderers:
                            temp_chart: !chart                            
                                series: 
                                    temp.max:
                                        color: '9BCDF1'
                                        fill: { color: '9BCDF1', to: temp.min }
                                        max: { color: orange, label: right }
                                    temp.avg:                                      
                                        label: right
                                    temp.min:
                                        color: '9BCDF1'
                                labels: temp.lbl
                                zero: { color: gray }

                            temp_current: !value
                                key: temp
                                serie: avg
                                select: last
                hours: !data
                    #source: !hourly {period: 168}
                    source: !simulator {}
                    renderer: !multi
                        renderers:
                            temp_chart: !chart
                                series:
                                    temp.avg:
                                        color: blue


