context:
    database: { url: 'localhost:/var/lib/firebird/2.0/data/wfrog.db' }
    units: 
        temp: F
        press: mmHg
        wind: kt
        rain: in        
renderer: !http    
    root: !include
        path: default/24hours.yaml
    renderers:
        24hours.html: !include
            path: default/24hours.yaml
        30days.html: !include
            path: default/30days.yaml
        365days.html: !include
            path: default/365days.yaml
    
