context:
    database: { url: 'file://database.db' }
    chart_defaults:
        #width: 270
        height: 125
        bgcolor: 70BDF5
        color: indigo
        text: indigo
        
renderer: !http    
    root: !template
        path: templates/current-stats.html
        mime: text/html
        renderer: !multi
            renderers:
                days: !data
                    #source: !daily { period: 30 }
                    source: !simulator {} 
                    renderer: !multi
                        renderers:
                            temp_chart: !chart                            
                                series: 
                                    temp.max:
                                        color: '9BCDF1'
                                        fill: { to: temp.min }
                                        max: { color: brown, text: brown, thickness: 0.5 }
                                    temp.avg:                                      
                                        last: { thickness: 5, style: 'o' }
                                    temp.min:
                                        color: '9BCDF1'
                                        min: { color: blue, text: blue, thickness: 0.5 }
                                labels: temp.lbl
                                zero: { color: gray, thickness: 0.5 }

                            temp_current: !value
                                key: temp
                                serie: avg
                                select: last
                hours: !data
                    #source: !hourly {period: 168}
                    source: !simulator {}
                    renderer: !multi
                        renderers:
                            temp_chart: !chart
                                series:
                                    temp.avg:
                                        color: blue


