station: !random-simulator {}

output: !http-out { url: 'http://localhost:8080/' }

logging:
    level: debug    
    handlers:
        default: 
            handler: !include 
                path: ../../wfcommon/config/loghandler.yaml
                variables:
                    process: wflogger

