#storage: !csv
#    path: /tmp/wfrog.csv

storage: !firebird { database: 'localhost:/var/lib/firebird/2.0/data/wfrog.db',
                     user: sysdba,
                     password: masterkey } 

#storage: !mysql { database: wfrog,
#                  host: localhost,
#                  user: root,
#                  password: root }
